# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

User.destroy_all
Listing.destroy_all
ActiveRecord::Base.connection.reset_pk_sequence!('users')
ActiveRecord::Base.connection.reset_pk_sequence!('listings')

demo = User.create!( email: 'User@Fake.com', first_name: 'Demo', last_name: 'User', password: '123456')
alex = User.create!( email: 'alex@wong.com', first_name: 'Alex', last_name: 'Wong', password: 'adminpassword')
tashi = User.create!( email: 'tashi@sangpo.com', first_name: 'Tashi', last_name: 'Sangpo', password: '123456')
nick = User.create!( email: 'nick@barr.com', first_name: 'Nick', last_name: 'Barr', password: 'password')
stella = User.create!( email: 'stella@choi.com', first_name: 'Stella', last_name: 'Choi', password: 'password')
andrew = User.create!( email: 'andrew@vito.com', first_name: 'Andrew', last_name: 'Vito', password: 'password')

file = URI.open('https://iibnb-seeds.s3.amazonaws.com/demopf.png')
demo.photo.attach(io: file, filename: 'demopf.png')

alexp = URI.open('https://iibnb-seeds.s3.amazonaws.com/profileicon/Alex.png')
nickp = URI.open('https://iibnb-seeds.s3.amazonaws.com/profileicon/Nick.png')
andrewp = URI.open('https://iibnb-seeds.s3.amazonaws.com/profileicon/Andrew.png')
stellap = URI.open('https://iibnb-seeds.s3.amazonaws.com/profileicon/Stella.jpg')
taship = URI.open('https://iibnb-seeds.s3.amazonaws.com/profileicon/Tashi.png')

alex.photo.attach(io: alexp, filename: 'Alex.png')
nick.photo.attach(io: nickp, filename: 'Nick.png')
andrew.photo.attach(io: andrewp, filename: 'Andrew.png')
stella.photo.attach(io: stellap, filename: 'Stella.jpg')
tashi.photo.attach(io: taship, filename: 'Tashi.png')





listing1 = Listing.create!(host_id: 2, title: "The Box", description: "Just a box", address: "Corner of Wall Street", guest_limit: 1, price: 100, bedrooms: 1, bathrooms: 1, latitude: 40.706064, longitude: -74.008782)
listing2 = Listing.create!(host_id: 1, title: "The Beach House", description: "Just a beach house", address: "Pebble Beach", guest_limit: 12, price: 620, bedrooms: 8, bathrooms: 6, latitude: 40.704502, longitude:-73.987215 )
listing3 = Listing.create!(host_id: 3, title: "The Cabin in the Woods", description: "It's a cabin in the woods", address: "Somewhere undisclosed", guest_limit: 6, price: 237, bedrooms: 3, bathrooms: 1.5, latitude:40.702105, longitude:-73.997019 )
listing4 = Listing.create!(host_id: 4, title: "The Battery", description: "TBA", address: "20 Battery Pl", guest_limit: 5, price: 170, bedrooms: 3, bathrooms: 1, latitude: 40.705644, longitude: -74.017992)
listing5 = Listing.create!(host_id: 5, title: "The Museum", description: "TBA", address: "11 W53rd", guest_limit: 8, price: 280, bedrooms: 4, bathrooms: 2, latitude: 40.761219, longitude: -73.976800)
listing6 = Listing.create!(host_id: 6, title: "The Washington", description: "TBA", address: "12 Washington Square Park", guest_limit: 5, price: 123, bedrooms: 3, bathrooms: 1.5, latitude: 40.731665, longitude: -73.997314)
listing7 = Listing.create!(host_id: 6, title: "The Hell's Kitchennette", description: "TBA", address: "448 W 48th St", guest_limit: 9, price: 210, bedrooms: 5, bathrooms: 2, latitude: 40.763053, longitude: -73.991528)
listing8 = Listing.create!(host_id: 5, title: "The Lincoln", address: "10 Lincoln Center Plaza", description: "TBA", guest_limit: 12, price: 382, bedrooms: 6, bathrooms: 3, latitude: 40.772181, longitude: -73.983445)
listing9 = Listing.create!(host_id: 4, title: "The Hamilton", address: "20 Hamilton Park", description: "TBA", guest_limit: 3, price: 80, bedrooms: 2, bathrooms: 1, latitude: 40.771405, longitude: -74.015152)
listing10 = Listing.create!(host_id: 3, title: "The Harlem", address: "250 Harlem East", description: "TBA", guest_limit: 8, price: 730, bedrooms: 4, bathrooms: 5, latitude: 40.811003, longitude: -73.946894)
listing11 = Listing.create!(host_id: 2, title: "The Hunter", address: "1 Hunters Point", description: "TBA", guest_limit: 2, price: 98, bedrooms: 2, bathrooms: 1, latitude: 40.747250, longitude: -73.949301)
listing12 = Listing.create!(host_id: 1, title: "The Virus", address: "102 Corona Avenue", description: "TBA", guest_limit: 1, price: 2020, bedrooms: 2, bathrooms: 1, latitude: 40.744285, longitude: -73.861519)
listing13 = Listing.create!(host_id: 2, title: "The Michael", address: "Bay Ridge", description: "TBA", guest_limit: 5, price: 92, bedrooms: 3, bathrooms: 1, latitude: 40.625487, longitude: -74.030020)
listing14 = Listing.create!(host_id: 2, title: "The Zoo", address: "Staten Island Zoo", description: "TBA", guest_limit: 10, price: 720, bedrooms: 10, bathrooms: 10, latitude: 40.624198, longitude: -74.0114123)
listing15 = Listing.create!(host_id: 1, title: "The Grave", address: "2 Gravesend", description: "TBA", guest_limit: 1, price: 20, bedrooms: 1, bathrooms: 1, latitude: 40.592709, longitude: -73.967536)
listing16 = Listing.create!(host_id: 4, title: "The Mission", address: "1 Mission District", description: "TBA", guest_limit: 8, price: 380, bedrooms: 5, bathrooms: 3, latitude: 37.757136, longitude: -122.414943)
listing17 = Listing.create!(host_id: 5, title: "The Sirloin", address: "9 Tenderloin", description: "TBA", guest_limit: 9, price: 490, bedrooms: 8, bathrooms: 3, latitude: 39.785116, longitude: -122.414426)
listing18 = Listing.create!(host_id: 5, title: "The Mighty Tree", address: "Heron's Head Park", description: "TBA", guest_limit: 7, price: 190, bedrooms: 3, bathrooms: 1, latitude: 37.737592, longitude: -122.372606)

listingphoto1 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/kelli-mcclintock-d21p_xkPoMA-unsplash.jpg')
listingphoto2 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/kadarius-seegars-DevJkLB3hWE-unsplash.jpg')
listingphoto3 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/kadarius-seegars-S6OvsSwm5sE-unsplash.jpg')
listingphoto4 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/kelli-mcclintock-ANp23FdOOls-unsplash.jpg')
listingphoto5 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/kelli-mcclintock-DcoB_NoNl6U-unsplash.jpg')
listingphoto6 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/kelli-mcclintock-GopRYASfsOc-unsplash.jpg')
listingphoto7 = URI.open('https://iibnb-seeds.s3.amazonaws.com/cb/brandable-box-8mCsyImZRGY-unsplash.jpg')
listingphoto8 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/1.jpg')
listingphoto9 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/2.jpg')
listingphoto10 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/3.jpg')
listingphoto11 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/4.jpg')
listingphoto12 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/5.jpg')
listingphoto13 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/6.jpg')
listingphoto14 = URI.open('https://iibnb-seeds.s3.amazonaws.com/bh/7.jpg')
listingphoto15 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin1.jpg')
listingphoto16 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin2.jpg')
listingphoto17 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin3.jpg')
listingphoto18 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin4.jpg')
listingphoto19 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin5.jpg')
listingphoto20 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin6.jpg')
listingphoto21 = URI.open('https://iibnb-seeds.s3.amazonaws.com/ch/Cabin7.jpg')


listingphoto22 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/1.jpg')
listingphoto23 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/2.jpg')
listingphoto24 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/3.jpg')
listingphoto25 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/4.jpg')
listingphoto26 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/5.jpg')
listingphoto27 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/6.jpg')
listingphoto28 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H/7.jpg')

listingphoto29 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H1.jpg')
listingphoto30 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H2.jpg')
listingphoto31 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H3.jpg')
listingphoto32 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H4.jpg')
listingphoto33 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H5.jpg')
listingphoto34 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H6.jpg')
listingphoto35 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H2/H7.jpg')

listingphoto36 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H1.jpg')
listingphoto37 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H2.jpg')
listingphoto38 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H3.jpg')
listingphoto39 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H4.jpg')
listingphoto40 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H5.jpg')
listingphoto41 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H6.jpg')
listingphoto42 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H3/H7.jpg')

listingphoto43 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H1.jpg')
listingphoto44 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H2.jpg')
listingphoto45 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H3.jpg')
listingphoto46 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H4.jpg')
listingphoto47 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H5.jpg')
listingphoto48 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H6.jpg')
listingphoto49 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H4/H7.jpg')

listingphoto50 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H1.jpg')
listingphoto51 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H2.jpg')
listingphoto52 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H3.jpg')
listingphoto53 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H4.jpg')
listingphoto54 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H5.jpg')
listingphoto55 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H6.jpg')
listingphoto56 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H5/H7.jpg')

listingphoto57 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H1.jpg')
listingphoto58 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H2.jpg')
listingphoto59 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H3.jpg')
listingphoto60 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H4.jpg')
listingphoto61 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H5.jpg')
listingphoto62 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H6.jpg')
listingphoto63 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H6/H7.jpg')

listingphoto64 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H1.jpg')
listingphoto65 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H2.jpg')
listingphoto66 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H3.jpg')
listingphoto67 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H4.jpg')
listingphoto68 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H5.jpg')
listingphoto69 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H6.jpg')
listingphoto70 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H7/H7.jpg')

listingphoto71 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H1.jpg')
listingphoto72 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H2.jpg')
listingphoto73 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H3.jpg')
listingphoto74 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H4.jpg')
listingphoto75 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H5.jpg')
listingphoto76 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H6.jpg')
listingphoto77 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H8/H7.jpg')

listingphoto78 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H1.jpg')
listingphoto79 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H2.jpg')
listingphoto80 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H3.jpg')
listingphoto81 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H4.jpg')
listingphoto82 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H5.jpg')
listingphoto83 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H6.jpg')
listingphoto84 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H9/H7.jpg')

listingphoto85 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H1.jpg')
listingphoto86 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H2.jpg')
listingphoto87 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H3.jpg')
listingphoto88 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H4.jpg')
listingphoto89 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H5.jpg')
listingphoto90 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H6.jpg')
listingphoto91 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H10/H7.jpg')

listingphoto92 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H1.jpg')
listingphoto93 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H2.jpg')
listingphoto94 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H3.jpg')
listingphoto95 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H4.jpg')
listingphoto96 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H5.jpg')
listingphoto97 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H6.jpg')
listingphoto98 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H11/H7.jpg')

listingphoto99 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/r-architecture-ujGLsMmXoBg-unsplash.jpg')
listingphoto100 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/living-room-4013531_1920.jpg')
listingphoto101 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/interior-2685518_1920.jpg')
listingphoto102 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/hotel-1979406_1920.jpg')
listingphoto103 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/bedroom-3778695_1920+(1).jpg')
listingphoto104 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/bed-6377145_1920.jpg')
listingphoto105 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H12/bed-1575491_1920.jpg')

listingphoto106 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H1.jpg')
listingphoto107 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H2.jpg')
listingphoto108 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H3.jpg')
listingphoto109 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H4.jpg')
listingphoto110 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H5.jpg')
listingphoto111 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H6.jpg')
listingphoto112 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H13/H7.jpg')

listingphoto113 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H1.jpg')
listingphoto114 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H2.jpg')
listingphoto115 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H3.jpg')
listingphoto116 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H4.jpg')
listingphoto117 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H5.jpg')
listingphoto118 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H6.jpg')
listingphoto119 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H14/H7.jpg')

listingphoto120 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H1.jpg')
listingphoto121 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H2.jpg')
listingphoto122 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H3.jpg')
listingphoto123 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H4.jpg')
listingphoto124 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H5.jpg')
listingphoto125 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H6.jpg')
listingphoto126 = URI.open('https://iibnb-seeds.s3.amazonaws.com/Homes/H15/H7.jpg')


listing1.photos.attach(io: listingphoto1, filename:'kelli-mcclintock-d21p_xkPoMA-unsplash.jpg')
listing1.photos.attach(io: listingphoto2, filename:'cb2.jpg')
listing1.photos.attach(io: listingphoto3, filename:'cb3.jpg')
listing1.photos.attach(io: listingphoto4, filename:'cb4.jpg')
listing1.photos.attach(io: listingphoto5, filename:'cb5.jpg')
listing1.photos.attach(io: listingphoto6, filename:'cb6.jpg')
listing1.photos.attach(io: listingphoto7, filename:'cb7.jpg')

listing2.photos.attach(io: listingphoto8, filename:'bh1.jpg')
listing2.photos.attach(io: listingphoto9, filename:'bh2.jpg')
listing2.photos.attach(io: listingphoto10, filename:'bh3.jpg')
listing2.photos.attach(io: listingphoto11, filename:'bh4.jpg')
listing2.photos.attach(io: listingphoto12, filename:'bh5.jpg')
listing2.photos.attach(io: listingphoto13, filename:'bh6.jpg')
listing2.photos.attach(io: listingphoto14, filename:'bh7.jpg')

listing3.photos.attach(io: listingphoto15, filename:'Cabin1.jpg')
listing3.photos.attach(io: listingphoto16, filename:'Cabin2.jpg')
listing3.photos.attach(io: listingphoto17, filename:'Cabin3.jpg')
listing3.photos.attach(io: listingphoto18, filename:'Cabin4.jpg')
listing3.photos.attach(io: listingphoto19, filename:'Cabin5.jpg')
listing3.photos.attach(io: listingphoto20, filename:'Cabin6.jpg')
listing3.photos.attach(io: listingphoto21, filename:'Cabin7.jpg')

listing16.photos.attach(io: listingphoto22, filename:'1.jpg')
listing16.photos.attach(io: listingphoto23, filename:'2.jpg')
listing16.photos.attach(io: listingphoto24, filename:'3.jpg')
listing16.photos.attach(io: listingphoto25, filename:'4.jpg')
listing16.photos.attach(io: listingphoto26, filename:'5.jpg')
listing16.photos.attach(io: listingphoto27, filename:'6.jpg')
listing16.photos.attach(io: listingphoto28, filename:'7.jpg')

listing4.photos.attach(io: listingphoto29, filename:'H1.jpg')
listing4.photos.attach(io: listingphoto30, filename:'H2.jpg')
listing4.photos.attach(io: listingphoto31, filename:'H3.jpg')
listing4.photos.attach(io: listingphoto32, filename:'H4.jpg')
listing4.photos.attach(io: listingphoto33, filename:'H5.jpg')
listing4.photos.attach(io: listingphoto34, filename:'H6.jpg')
listing4.photos.attach(io: listingphoto35, filename:'H7.jpg')

listing5.photos.attach(io: listingphoto36, filename:'H1.jpg')
listing5.photos.attach(io: listingphoto37, filename:'H2.jpg')
listing5.photos.attach(io: listingphoto38, filename:'H3.jpg')
listing5.photos.attach(io: listingphoto39, filename:'H4.jpg')
listing5.photos.attach(io: listingphoto40, filename:'H5.jpg')
listing5.photos.attach(io: listingphoto41, filename:'H6.jpg')
listing5.photos.attach(io: listingphoto42, filename:'H7.jpg')

listing6.photos.attach(io: listingphoto43, filename:'H1.jpg')
listing6.photos.attach(io: listingphoto44, filename:'H2.jpg')
listing6.photos.attach(io: listingphoto45, filename:'H3.jpg')
listing6.photos.attach(io: listingphoto46, filename:'H4.jpg')
listing6.photos.attach(io: listingphoto47, filename:'H5.jpg')
listing6.photos.attach(io: listingphoto48, filename:'H6.jpg')
listing6.photos.attach(io: listingphoto49, filename:'H7.jpg')

listing7.photos.attach(io: listingphoto50, filename:'H1.jpg')
listing7.photos.attach(io: listingphoto51, filename:'H2.jpg')
listing7.photos.attach(io: listingphoto52, filename:'H3.jpg')
listing7.photos.attach(io: listingphoto53, filename:'H4.jpg')
listing7.photos.attach(io: listingphoto54, filename:'H5.jpg')
listing7.photos.attach(io: listingphoto55, filename:'H6.jpg')
listing7.photos.attach(io: listingphoto56, filename:'H7.jpg')

listing8.photos.attach(io: listingphoto57, filename:'H1.jpg')
listing8.photos.attach(io: listingphoto58, filename:'H2.jpg')
listing8.photos.attach(io: listingphoto59, filename:'H3.jpg')
listing8.photos.attach(io: listingphoto60, filename:'H4.jpg')
listing8.photos.attach(io: listingphoto61, filename:'H5.jpg')
listing8.photos.attach(io: listingphoto62, filename:'H6.jpg')
listing8.photos.attach(io: listingphoto63, filename:'H7.jpg')

listing9.photos.attach(io: listingphoto64, filename:'H1.jpg')
listing9.photos.attach(io: listingphoto65, filename:'H2.jpg')
listing9.photos.attach(io: listingphoto66, filename:'H3.jpg')
listing9.photos.attach(io: listingphoto67, filename:'H4.jpg')
listing9.photos.attach(io: listingphoto68, filename:'H5.jpg')
listing9.photos.attach(io: listingphoto69, filename:'H6.jpg')
listing9.photos.attach(io: listingphoto70, filename:'H7.jpg')

listing10.photos.attach(io: listingphoto71, filename:'H1.jpg')
listing10.photos.attach(io: listingphoto72, filename:'H2.jpg')
listing10.photos.attach(io: listingphoto73, filename:'H3.jpg')
listing10.photos.attach(io: listingphoto74, filename:'H4.jpg')
listing10.photos.attach(io: listingphoto75, filename:'H5.jpg')
listing10.photos.attach(io: listingphoto76, filename:'H6.jpg')
listing10.photos.attach(io: listingphoto77, filename:'H7.jpg')

listing11.photos.attach(io: listingphoto78, filename:'H1.jpg')
listing11.photos.attach(io: listingphoto79, filename:'H2.jpg')
listing11.photos.attach(io: listingphoto80, filename:'H3.jpg')
listing11.photos.attach(io: listingphoto81, filename:'H4.jpg')
listing11.photos.attach(io: listingphoto82, filename:'H5.jpg')
listing11.photos.attach(io: listingphoto83, filename:'H6.jpg')
listing11.photos.attach(io: listingphoto84, filename:'H7.jpg')

listing12.photos.attach(io: listingphoto85, filename:'H1.jpg')
listing12.photos.attach(io: listingphoto86, filename:'H2.jpg')
listing12.photos.attach(io: listingphoto87, filename:'H3.jpg')
listing12.photos.attach(io: listingphoto88, filename:'H4.jpg')
listing12.photos.attach(io: listingphoto89, filename:'H5.jpg')
listing12.photos.attach(io: listingphoto90, filename:'H6.jpg')
listing12.photos.attach(io: listingphoto91, filename:'H7.jpg')

listing13.photos.attach(io: listingphoto92, filename:'H1.jpg')
listing13.photos.attach(io: listingphoto93, filename:'H2.jpg')
listing13.photos.attach(io: listingphoto94, filename:'H3.jpg')
listing13.photos.attach(io: listingphoto95, filename:'H4.jpg')
listing13.photos.attach(io: listingphoto96, filename:'H5.jpg')
listing13.photos.attach(io: listingphoto97, filename:'H6.jpg')
listing13.photos.attach(io: listingphoto98, filename:'H7.jpg')

listing14.photos.attach(io: listingphoto99, filename:'H1.jpg')
listing14.photos.attach(io: listingphoto100, filename:'H2.jpg')
listing14.photos.attach(io: listingphoto101, filename:'H3.jpg')
listing14.photos.attach(io: listingphoto102, filename:'H4.jpg')
listing14.photos.attach(io: listingphoto103, filename:'H5.jpg')
listing14.photos.attach(io: listingphoto104, filename:'H6.jpg')
listing14.photos.attach(io: listingphoto105, filename:'H7.jpg')

listing15.photos.attach(io: listingphoto106, filename:'H1.jpg')
listing15.photos.attach(io: listingphoto107, filename:'H2.jpg')
listing15.photos.attach(io: listingphoto108, filename:'H3.jpg')
listing15.photos.attach(io: listingphoto109, filename:'H4.jpg')
listing15.photos.attach(io: listingphoto110, filename:'H5.jpg')
listing15.photos.attach(io: listingphoto111, filename:'H6.jpg')
listing15.photos.attach(io: listingphoto112, filename:'H7.jpg')

listing17.photos.attach(io: listingphoto113, filename:'H1.jpg')
listing17.photos.attach(io: listingphoto114, filename:'H2.jpg')
listing17.photos.attach(io: listingphoto115, filename:'H3.jpg')
listing17.photos.attach(io: listingphoto116, filename:'H4.jpg')
listing17.photos.attach(io: listingphoto117, filename:'H5.jpg')
listing17.photos.attach(io: listingphoto118, filename:'H6.jpg')
listing17.photos.attach(io: listingphoto119, filename:'H7.jpg')

listing18.photos.attach(io: listingphoto120, filename:'H1.jpg')
listing18.photos.attach(io: listingphoto121, filename:'H2.jpg')
listing18.photos.attach(io: listingphoto122, filename:'H3.jpg')
listing18.photos.attach(io: listingphoto123, filename:'H4.jpg')
listing18.photos.attach(io: listingphoto124, filename:'H5.jpg')
listing18.photos.attach(io: listingphoto125, filename:'H6.jpg')
listing18.photos.attach(io: listingphoto126, filename:'H7.jpg')




